# -*- coding: utf-8 -*-
"""groq_implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DqCHAaQPQbLiMl_dKSlKJ9oh7Igvwi34
"""

from llama_index.llms.groq import Groq
import json
import pandas as pd

file_path = "Data/general_scores_by_city_year.json"
with open(file_path, "r") as file:
    data = json.load(file)

df = pd.DataFrame(data)
df_2022 = df[df["date_label"] == 2022]

top_city = df_2022.nlargest(1, "Average_General_Score")[["geo_label_citystate", "Average_General_Score"]]["geo_label_citystate"]
top_city = top_city.values[0]
prompt_input = f"Evaluate {top_city} in terms of its social, economic, and health factors. In the first paragraph, dive into the city’s key strengths, including aspects like quality of life, economic opportunities, and public health initiatives, being specific and using cited statistics. In the second paragraph, discuss how these factors contribute to the city’s overall livability and well-being, including any notable policies or initiatives that support social equity, economic growth, and health outcomes. Keep the response balanced and specific with examples and statistics, noting both strengths and any areas for improvement where relevant."

llm = Groq(model = "gemma2-9b-it", api_key= "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")
response = llm.complete(prompt= prompt_input, temperature = .8, max_completion_tokens = 2048)

#save response as a JSON file
response_data = {
    "response": response.text,  #access the text from the response object
}

output_file_path = "groq_response.json"
with open(output_file_path, "w") as outfile:
    json.dump(response_data, outfile, indent=4) #indent makes the json file more readable.